# Generated by Django 3.1.2 on 2020-10-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(help_text='measure in North and South')),
                ('Longitude', models.FloatField(help_text='measure in East and West')),
                ('Unique_Squirrel_ID', models.CharField(help_text='unique squirrel id with location, date and time', max_length=20)),
                ('Shift', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon')], help_text='morning or afternoon when sighted', max_length=2)),
                ('Date', models.DateField(help_text='pass in date object')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of the squirrel', max_length=15, null=True)),
            ],
        ),
    ]
