# Generated by Django 3.1.2 on 2020-10-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0003_auto_20201017_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(default=None, help_text='unique squirrel id with location, date and time', max_length=20, primary_key=True, serialize=False),
        ),
    ]
